### ISSUE TITLE
Warnings/Errors from the rust core?

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-node#325]
```
thread '<unnamed>' panicked at 'failed to setup idle: Io(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })', src/dc_imap.rs:1063:29
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
fetch err: Io(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })
thread '<unnamed>' panicked at 'failed to setup idle: Io(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })', src/dc_imap.rs:1063:29
thread '<unnamed>' panicked at 'failed to setup idle: Io(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })', src/dc_imap.rs:1063:29
```

Sometimes it crashes while logging out:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:999:5
fatal runtime error: failed to initiate panic, error 5
```

On my test account it crashes as soon as I select a chat or just start it when connected to the internet
```
> electron . --debug --log-debug --log-to-console --disable-http-cache

Logfile: /home/simon/.config/DeltaChat/logs/2019-05-21T20:49:28.807Z.log
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
{ message: 'Select a chat or create a new chat' }
main/index INFO [] cwd /home/simon/.config/DeltaChat
main/deltachat/login INFO [] Using deltachat instance /home/simon/.config/DeltaChat/7331407465737472756e2e6f72672020
main/ipc DEBUG [] RENDER
main/menu INFO [] rebuilding menu with locale en
main/mainWindow INFO [] toggleDevTools
main/deltachat/login INFO [] Ready
main/deltachat/login INFO [] dc_get_info { deltachat_core_version: 'v0.43.0',
  sqlite_version: '3.27.2',
  sqlite_thread_safe: '1',
  compile_date: 'Apr 26 2019, 00:51:50',
  arch: '64',
  number_of_chats: '25',
  number_of_chat_messages: '5766',
  messages_in_contact_requests: '48',
  number_of_contacts: '40',
  database_dir:
   '/home/simon/.config/DeltaChat/7331407465737472756e2e6f72672020/db.sqlite',
  database_version: '55',
  blobdir:
   '/home/simon/.config/DeltaChat/7331407465737472756e2e6f72672020/db.sqlite-blobs',
  display_name: '0',
  is_configured: '1',
  entered_account_settings: 's1@testrun.org   0:***:0:0 0:0:0:0 0',
  used_account_settings:
   's1@testrun.org s1@testrun.org:***:testrun.org:993 s1@testrun.org:***:testrun.org:25 AUTH_NORMAL IMAP_SSL SMTP_STARTTLS',
  inbox_watch: '1',
  sentbox_watch: '1',
  mvbox_watch: '1',
  mvbox_move: '1',
  folders_configured: '3',
  configured_sentbox_folder: '<unset>',
  configured_mvbox_folder: '<unset>',
  mdns_enabled: '0',
  e2ee_enabled: '1',
  private_key_count: '1',
  public_key_count: '35',
  fingerprint: '59EB66D64502A00C1FCA3BFCB7C103D5CAB13454',
  level: 'awesome' }
main/ipc DEBUG [] RENDER
main/deltachat/login DEBUG [] ALL event { event: 100,
  data1: 0,
  data2:
   'Opened "/home/simon/.config/DeltaChat/7331407465737472756e2e6f72672020/db.sqlite".' }
main/deltachat/login DEBUG [] ALL event { event: 100, data1: 0, data2: 'INBOX-jobs started...' }
main/deltachat/login DEBUG [] ALL event { event: 100, data1: 0, data2: 'SMTP-jobs started...' }
main/deltachat/login DEBUG [] ALL event { event: 100,
  data1: 0,
  data2: 'INBOX-job #1, action 200 started...' }
main/deltachat/login DEBUG [] ALL event { event: 100, data1: 0, data2: 'SMTP-jobs ended.' }
main/deltachat/login DEBUG [] ALL event { event: 100, data1: 0, data2: 'SMTP-idle started...' }
main/state INFO [] Saving state to /home/simon/.config/DeltaChat/config.json
{ message: 'Select a chat or create a new chat' }
main/ipc DEBUG [] RENDER
init: 1969.486ms
main/deltachat/login DEBUG [] ALL event { event: 100,
  data1: 0,
  data2:
   'IMAP-capabilities: CHILDREN NAMESPACE IMAP4rev1 ENABLE CATENATE QRESYNC CONTEXT=SEARCH THREAD=ORDEREDSUBJECT CONDSTORE SASL-IR UNSELECT ESEARCH MOVE LOGIN-REFERRALS ESORT WITHIN SORT THREAD=REFS LITERAL+ I18NLEVEL=1 URL-PARTIAL LIST-STATUS LIST-EXTENDED IDLE MULTIAPPEND SPECIAL-USE THREAD=REFERENCES ID SEARCHRES UIDPLUS SORT=DISPLAY BINARY' }
``` 
also name in the error message when offline looks strange
![errorname](https://user-images.githubusercontent.com/18725968/58130088-804cf880-7c1b-11e9-842d-a915c5ad2814.png)

**Comment by ralphtheninja** [comment]
What os are you using? Are you sure you're using the latest rust core?

**Comment by ralphtheninja** [comment]
> also name in the error message when offline looks strange

This looks like some problems with null termination.

**Comment by Simon-Laux** [comment]
feb95308bc00ca419675e3201d69e3414c67d25a
```
commit feb95308bc00ca419675e3201d69e3414c67d25a
Author: Lars-Magnus Skog <ralphtheninja@riseup.net>
Date:   Sat May 18 23:27:18 2019 +0200

    chore: call cargo update before build (#324)
    
    * chore: call cargo update before build
    
    * refactor opts
```

**Comment by Simon-Laux** [comment]
I'll keep this issue updated and tell what errors still appear in the next days after updating to f1f2b22a201bb044ba4b6f41385bdce43a087af0

**Comment by Simon-Laux** [comment]
crash on open is still there with message
```
failed to close connection: Bad("No mailbox selected (0.000 + 0.000 secs).")
```

**Comment by Simon-Laux** [comment]
![strangeDataInImapError](https://user-images.githubusercontent.com/18725968/58348134-13767000-7e60-11e9-9ada-a151028492e1.png)

**Comment by ralphtheninja** [comment]
Closing this. Please post specific errors in separate issues so we can fix them one at a time.
