### ISSUE TITLE
Unit tests fail for group chat

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-node#330]
Just making a note of this for now

```
ok 196 timestamp set
not ok 197 custom new group message
  ---
    operator: equal
    expected: 'Custom new group message, yo!'
    actual:   'Hello, I\'ve just created the group "groupchat1111" for us.'
    at: test (/home/lms/src/deltachat/deltachat-node/test/index.js:404:5)
    stack: |-
      Error: custom new group message
          at Test.assert [as _assert] (/home/lms/src/deltachat/deltachat-node/node_modules/tape/lib/test.js:226:54)
          at Test.bound [as _assert] (/home/lms/src/deltachat/deltachat-node/node_modules/tape/lib/test.js:77:32)
          at Test.equal (/home/lms/src/deltachat/deltachat-node/node_modules/tape/lib/test.js:386:10)
          at Test.bound [as is] (/home/lms/src/deltachat/deltachat-node/node_modules/tape/lib/test.js:77:32)
          at test (/home/lms/src/deltachat/deltachat-node/test/index.js:404:5)
          at dc.open.err (/home/lms/src/deltachat/deltachat-node/test/index.js:439:7)
          at binding.dcn_open.err (/home/lms/src/deltachat/deltachat-node/lib/deltachat.js:5:3183)
  ...
```

**Comment by ralphtheninja** [comment]
Temporarily disabled these since they are related to the string table.
