### ISSUE TITLE
example-binding.js broken

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-node#37]
I guess it's because of the renaming/refactoring of the binding methods, but didn't test it with the prefixed method names yet.

```
$ node example-binding.js --email xxx --password xxx
Logging in with xxx xxx
result from dcn_context_new: [External]
/home/xxx/xxx/deltachat-node-jikstra/example-binding.js:19
res = binding.dcn_set_event_handler(dcn_context, (event, data1, data2) => {
              ^

TypeError: binding.dcn_set_event_handler is not a function
    at Object.<anonymous> (/home/xxx/xxx/deltachat-node-jikstra/example-binding.js:19:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
```

**Comment by ralphtheninja** [comment]
https://github.com/deltachat/deltachat-node/commit/1c1e6ccbc0589b8c230c25f0646d3c8a75fcc352

**Comment by ralphtheninja** [comment]
Sorry about this. I'm currently only using example.js, forgot to update.
