### ISSUE TITLE
Fails on build if we try to build from git+https

### ISSUE THREAD

**Issue by Jikstra** [deltachat/deltachat-node#536]
```
> node scripts/postinstall.js

postinstall: not windows, so skipping!
[i] Didn't find already build typescript bindings. Trying to transpile them. If this fail, make sure typescript is installed ;)
[i] running `npm run build:bindings:ts`

> deltachat-node@1.70.0 build:bindings:ts /home/kerle/Coding/deltachat-desktop/node_modules/deltachat-node
> tsc

lib/context.ts:11:18 - error TS7016: Could not find a declaration file for module 'lodash.pick'. '/home/kerle/Coding/deltachat-desktop/node_modules/lodash.pick/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/lodash.pick` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash.pick';`

11 import pick from 'lodash.pick'
                    ~~~~~~~~~~~~~


Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! deltachat-node@1.70.0 build:bindings:ts: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the deltachat-node@1.70.0 build:bindings:ts script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kerle/.npm/_logs/2022-02-01T14_53_16_330Z-debug.log
child_process.js:682
    throw err;
    ^

Error: Command failed: npm run build:bindings:ts
    at checkExecSyncError (child_process.js:643:11)
    at execSync (child_process.js:679:15)
    at run (/home/kerle/Coding/deltachat-desktop/node_modules/deltachat-node/scripts/install.js:7:3)
    at Object.<anonymous> (/home/kerle/Coding/deltachat-desktop/node_modules/deltachat-node/scripts/install.js:26:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  status: 2,
  signal: null,
  output: [ null, null, null ],
  pid: 26116,
  stdout: null,
  stderr: null
}
```

**Comment by Simon-Laux** [comment]
we should probably move getSystemInfo to core to the account manager. for now we could just use plain js, we don't really need lodash at for this task: https://github.com/deltachat/deltachat-node/blob/master/lib/context.ts#L503
